### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by PrimeTDMomega**
I'll make a section for ratted clients later.
Also Paragon, Lambda, Kami Blue and Meteor to an extent are all not "Java Clients" they're built with Gradle but are made in Kotlin, maybe exception for Meteor but a lot of clients aren't categorized correctly and not categorized enough.

### CODE REVIEW

**Comment by PrimeTDMomega** [comment]
Can you commit this

**Comment by Maniacsan** [comment]
I'll do it later today

**Comment by PrimeTDMomega** [comment]
make a discord

**Review by Maniacsan — APPROVED** [review]

**Comment by Maniacsan** [comment]
@PrimeTDMomega 
> I'll make a section for ratted clients later.
I think its best to make a different markdown file for that.
> Also Paragon, Lambda, Kami Blue and Meteor to an extent are all not "Java Clients" they're built with Gradle but are made in Kotlin
I'm aware. The project states hack clients not java.
> clients aren't categorized correctly and not categorized enough.
It would be very difficult to manage this. Right now it's alphabetical so there's no bias of what client is better.
> make a discord
https://discord.gg/BH76jvEsVS

**Pull request merged**
